name: Cypress Tests

on: push
env:
  FRONTEND_PORT: 5000
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  VITE_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GOOGLE_LOGIN_REDIRECT_URI: http://localhost:3000/login
  VITE_GOOGLE_LOGIN_REDIRECT_URI: http://localhost:3000/login
  MONGO_URI: mongodb://localhost:27017/?writeConcern=majority
  POSTGRES_URI: postgresql://postgres:mysecretpassword@localhost:5432/postgres
  JWT_SECRET: abc123
jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: mysecretpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 6.0
      - name: Generate Data
        run: npm i && npm run data:testuser && npm run data:generate
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          wait-on: "http://localhost:5000"
      - name: Deploy to production
        run: |
          curl --request GET \
          --url "${{ secrets.RENDER_DEPLOY_HOOK }}"
